cache:
  paths:
    - benchmarks/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - '! [ -e ./benchmarks/dacapo-2006-10-MR2.jar ] && mkdir -p benchmarks && wget https://downloads.sourceforge.net/project/dacapobench/archive/2006-10-MR2/dacapo-2006-10-MR2.jar -O benchmarks/dacapo-2006-10-MR2.jar'
    
build:basebasenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseNoGC

build:fastadaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g FastAdaptiveNoGC

build:fulladaptivenogc:
  stage: build
  script:
    - python scripts/testMMTk.py -g FullAdaptiveNoGC

build:basebasenogcjavabuild:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseNoGC --java-build

build:basebasesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseSemiSpace

build:fastadaptivesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g FastAdaptiveSemiSpace

build:fulladaptivesemispace:
  stage: build
  script:
    - python scripts/testMMTk.py -g FullAdaptiveSemiSpace

build:basebasesemispacejavabuild:
  stage: build
  script:
    - python scripts/testMMTk.py -g BaseBaseSemiSpace --java-build
